### ISSUE TITLE
Error(s) in loading state_dict for TripletsExtractorBERTOnly

### ISSUE THREAD

**Issue by DraymondHIT** [sberbank-ai/DetIE#4]
HI~

I tried to run a demo without training. Here is `demo.py` (put at DetIE/):
```
from modules.model.models import TripletsExtractorBERTOnly
from modules.model.apply import pprint_triplets

TEST_TEXTS = [
    "This is how Agent Archer received a medal from the US.",
    "Alexander Pushkin was shot at a duel in St. Petersburg.",
    "The assault rifle is one of the very popular weapons in the Sahara desert.",
    "Bill Gates owns Microsoft Corporation.",
    "Lindon fictional universe where entity is from legendarium, The Boeing Company produces 747, "
    "population of Ukraine has census Ukrainian Census (2020), Bellecour is on Lyon Metro Line D, "
    "Vierwaldstättersee uses transport by boat, Wang Mang follows religion Confucianism.",
    "Фоллаут есть отличная постапокалиптическая игра",
    "Roses are red. Violets are blue. Cleaning automatic rifles is the only thing I ever do.",
]


def main():
    best_ckpt_path = "results/logs/default/version_243/checkpoints/best.ckpt"
    best_hparams_path = "results/logs/default/version_243/hparams.yaml"
    model = TripletsExtractorBERTOnly.load_from_checkpoint(checkpoint_path=best_ckpt_path, hparams_file=best_hparams_path)
    # texts = list(cfg.model.viz_sentences)
    triplets = model.predict(list(TEST_TEXTS))
    pprint_triplets(TEST_TEXTS, triplets)

if __name__ == "__main__":
    main()
```

However, I met something error about `TripletsExtractorBERTOnly`:
```
Traceback (most recent call last):
  File "E:/github/DetIE/demo.py", line 44, in <module>
    main()
  File "E:/github/DetIE/demo.py", line 26, in main
    model = TripletsExtractorBERTOnly.load_from_checkpoint(checkpoint_path=best_ckpt_path, hparams_file=best_hparams_path)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\core\saving.py", line 156, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\core\saving.py", line 204, in _load_model_state
    keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "C:\Users\hp\AppData\Roaming\Python\Python36\site-packages\torch\nn\modules\module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TripletsExtractorBERTOnly:
	Missing key(s) in state_dict: "pretrained_encoder.pooler.dense.weight", "pretrained_encoder.pooler.dense.bias". 
	Unexpected key(s) in state_dict: "pretrained_encoder.embeddings.position_ids". 
```

Could you help me with the error? Thank you very much.

**Comment by alexeyev** [comment]
Hi, will get back to you, can't reproduce so far.

**Comment by alexeyev** [comment]
Please make sure the required libraries' versions match those listed in `context/requirements.txt`.

The following list of commands should lead to the successful execution of `demo.py`:

```bash

docker build -t detie .
nvidia-docker run  -p 8808:8808 -v `pwd`:/project -it detie:latest bash
gdown 1qgF2GHQeZ_gPg3QlmD_s9foN_P2d1Q1I
apt-get install p7zip-full
7z x version_243.7z
nano demo.py
<paste the updated demo.py code>
python demo.py
```

Updated `demo.py`:

```python

from modules.model.models import TripletsExtractorBERTOnly
from modules.model.apply import pprint_triplets

TEST_TEXTS = [
    "This is how Agent Archer received a medal from the US.",
    "Alexander Pushkin was shot at a duel in St. Petersburg.",
    "Bill Gates owns Microsoft Corporation.",
    "Vierwaldstättersee uses transport by boat, Wang Mang follows religion Confucianism.",
    "Фоллаут есть отличная постапокалиптическая игра",
]


def main():
    best_ckpt_path = "version_243/checkpoints/best.ckpt"
    best_hparams_path = "version_243/hparams.yaml"
    model = TripletsExtractorBERTOnly.load_from_checkpoint(checkpoint_path=best_ckpt_path, hparams_file=best_hparams_path)
    triplets = model.predict(list(TEST_TEXTS))
    pprint_triplets(TEST_TEXTS, triplets)


if __name__ == "__main__":
    main()

```

**Comment by DraymondHIT** [comment]
I'm so sorry that some libraries' versions of mine are wrong. That's my fault. Thank you very much!

**Comment by DraymondHIT** [comment]
I'm so sorry that some libraries' versions of mine are wrong. That's my fault. Thank you very much!
